/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-10-04 16:45:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>LMS</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/master.css\">\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/master.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"resources/js/main.js\"></script>\r\n");
      out.write("  <link href=\"/resources/css/main.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"getList('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'), divCreate(), otherClass(), getAjax('https://api.ipify.org','format=json', 'getPublicIp')\">\r\n");
      out.write("\r\n");
 Date date = new Date(); 
SimpleDateFormat simpleDate = new SimpleDateFormat("yyyy-MM-dd");
String strdate = simpleDate.format(date);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"hiddenBox\">\r\n");
      out.write("<input type='hidden' name='mbType' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li><a href=\"main\" id=\"test\" style=\"color: white;\"><img\r\n");
      out.write("                  src=\"resources/images/eljl_LOGO_final.png\"\r\n");
      out.write("                  style=\"height: 30px; width: 100px;\" /></a></li>\r\n");
      out.write("        <li class=\"dropdown\" id=\"user\" style = \"display:none; height:40px; padding-top:6px;\" >\r\n");
      out.write("            <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"> <p><span class=\"glyphicon glyphicon-plus-sign\"><span class=\"caret\"></span></span></p> </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\" id=\"classMenu\">\r\n");
      out.write("              <li><a data-toggle=\"modal\" data-target=\"#createClass1\"><span class=\"glyphicon glyphicon-plus\" > Class</span></a></li> \r\n");
      out.write("              \r\n");
      out.write("              <li onClick=\"deleteClassList()\"><a data-toggle=\"modal\" data-target=\"#deleteClass\"><span class=\"glyphicon glyphicon-trash\" > Delete</span></a></li>                        \r\n");
      out.write("           </ul>\r\n");
      out.write("       </li>\r\n");
      out.write("        <li><a href=\"calendar\" style=\"margin-top:5px;\">Calender</a></li>\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\" style=\"margin-top:5px;\">\r\n");
      out.write("        <li><a href=\"#\" onClick=\"logOut('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"><span class=\"glyphicon glyphicon-log-in\" > 로그아웃</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("  \r\n");
      out.write("<div class=\"container-fluid text-center\" style = \"margin-left:5%;\">    \r\n");
      out.write("  <div class=\"row content\">\r\n");
      out.write("  <hr>\r\n");
      out.write("    <div class=\"col-sm-1 text-left\"> </div>\r\n");
      out.write("    <div class=\"col-sm-10 text-left\"> \r\n");
      out.write("    \r\n");
      out.write("   		<div class = \"myClassList\">\r\n");
      out.write("        <div >\r\n");
      out.write("        <div class = \"bar\">내 강좌 목록 </div></div>\r\n");
      out.write("  	  <br>\r\n");
      out.write("      <div id=\"myClass\" ></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-sm-10 text-left\" style = \"margin-left:8.5%;\"> \r\n");
      out.write("     <div class = \"bar2\">다른 강좌 목록</div>\r\n");
      out.write("    	<br>\r\n");
      out.write("      <div id =\"otherClassList\" ></div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<!-- 클래스 생성 모달창 첫번째 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"createClass1\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" onClick=\"deleteValue()\" >&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">강좌 생성(1/2) </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body1\"><br>\r\n");
      out.write("          <p class = \"classCreate1\">학과 명</p>\r\n");
      out.write("             <input type=\"text\" name=\"csName\" class=\"textBox\">\r\n");
      out.write("           <p class = \"classCreate1\">강좌 명</p>\r\n");
      out.write("             <input type=\"text\" name=\"newOpName\" class=\"textBox\">\r\n");
      out.write("           <p class = \"classCreate1\">시작 날짜</p>\r\n");
      out.write("             <input type=\"date\" name=\"startDate\" min=\"");
      out.print(strdate );
      out.write("\" class=\"dateBox\" >\r\n");
      out.write("            <p class = \"classCreate1\">종료 날짜</p>\r\n");
      out.write("             <input type=\"date\" name=\"endDate\"  min=\"");
      out.print(strdate );
      out.write("\" onblur=\"endDateCheck()\" class=\"dateBox\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" data-toggle=\"modal\" data-target=\"#createClass2\" onClick=\"\">다음</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" onClick=\"deleteValue()\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- 클래스 생성 모달창 두번째 -->\r\n");
      out.write("  <div style=\"overflow:scroll;\" class=\"modal fade\" id=\"createClass2\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">강좌 생성(2/2) </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body2\" id=\"modal-body\"><br>\r\n");
      out.write("          <p class = \"classCreate2\">성적관리<a onClick=\"addCategory()\"><span class=\"glyphicon glyphicon-plus\" ></span></a></p>\r\n");
      out.write("        \r\n");
      out.write("          <div id=\"modalBox\"></div>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("         <br>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" data-toggle=\"modal\" data-target=\"#createClass1\" >이전</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" onClick=\"createClass()\">생성</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" onClick=\"deleteValue()\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write(" <!-- 삭제 모달창 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"deleteClass\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">강좌 삭제 </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        \r\n");
      out.write("             <table class=\"table table-striped\">\r\n");
      out.write("          <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>삭제할 강좌 목록</th>\r\n");
      out.write("              <th>분류</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("          <tbody id=\"deleteClassBox\">\r\n");
      out.write("      \r\n");
      out.write("          </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("        \r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" onClick=\"getList()\">닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  \r\n");
      out.write("  <!-- 수강신청 모달창-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"joinClass\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" onClick=\"deleteValue()\" >&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">수강신청 </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class = \"modal-body\">수강신청 하시겠습니까?</div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" onClick=\"joinClass()\">예</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" >아니오</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  \r\n");
      out.write("  <!-- 수강 취소 모달창-->\r\n");
      out.write("  <div class=\"modal fade\" id=\"cancelClass\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" >&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">수강 취소 </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class = \"modal-body\">해당 강좌를 취소하시겠습니까?</div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" onClick=\"cancelClass(number)\">예</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" >아니오</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
