/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-10-04 16:45:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class stream_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Stream</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"http://humy2833.dothome.co.kr/customizing.html#\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/vue/dist/vue.js\"></script>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/master.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function NoticeOutput(){\r\n");
      out.write("	let mbId = document.getElementsByName(\"mbId\")[0];\r\n");
      out.write("	let csCode = document.getElementsByName(\"csCode\")[0];\r\n");
      out.write("	let opCode = document.getElementsByName(\"opCode\")[0];\r\n");
      out.write("	\r\n");
      out.write("	console.log(mbId.value);\r\n");
      out.write("	console.log(csCode.value);\r\n");
      out.write("	console.log(opCode.value);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("a:hover {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#test : hover {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("/* Remove the navbar's default margin-bottom and rounded borders */\r\n");
      out.write(".navbar {\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	border-radius: 0;\r\n");
      out.write("	background-color: #375a7f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set height of the grid so .sidenav can be 100% (adjust as needed) */\r\n");
      out.write(".row.content {\r\n");
      out.write("	height: 450px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set gray background color and 100% height */\r\n");
      out.write(".sidenav {\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set black background color, C and some padding */\r\n");
      out.write("footer {\r\n");
      out.write("	background-color: #555;\r\n");
      out.write("	color: blue;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* On small screens, set height to 'auto' for sidenav and grid */\r\n");
      out.write("@media screen and (max-width: 767px) {\r\n");
      out.write("	.sidenav {\r\n");
      out.write("		height: auto;\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	.row.content {\r\n");
      out.write("		height: auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#classTitle {\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	background-color: #EBF7FF;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공지사항 제목칸 */\r\n");
      out.write("#titlebox{\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	width: 400px; /* 100% */\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	margin-bottom: -2px;\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("	border-width: 4px;\r\n");
      out.write("	border-color: skyblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공지사항 작성칸 */\r\n");
      out.write("#textbox {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	width: 400px; /* 100% */\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("	border-width: 4px;\r\n");
      out.write("	border-color: skyblue;\r\n");
      out.write("	word-break:normal; /* 줄바꿈 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 마감과제일정 글자영역 */\r\n");
      out.write("#scfontbox-sfb{\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("	margin-left: 95px;\r\n");
      out.write("	\r\n");
      out.write("	float: left; /* 가로정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 퀴즈일정 글자영역 */\r\n");
      out.write("#scfontbox-sf{\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("	margin-left: 275px;\r\n");
      out.write("	\r\n");
      out.write("	float: left; /* 가로정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 기타일정 글자영역 */\r\n");
      out.write("#scfontbox-sb{\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("	margin-left: 295px;\r\n");
      out.write("	\r\n");
      out.write("	float: left; /* 가로정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 일정글자 */\r\n");
      out.write("#scfont{\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	margin-top: 7px;\r\n");
      out.write("	margin-left: 318px;\r\n");
      out.write("	background-color: #5AAEFF;\r\n");
      out.write("	border-color: transparent; /* 박스 테두리 투명 */\r\n");
      out.write("	color: #FFFFFF;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 일정박스 */\r\n");
      out.write(".col-sm-4{\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	margin-right: 60px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	border: 2px solid #C7C6FF;\r\n");
      out.write("	box-shadow: 2px 3px 5px #999; /* h-offset v-offset blur spread color type */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 일정박스영역 */\r\n");
      out.write(".row{\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	margin-bottom: 50px;\r\n");
      out.write("	margin-left: 55px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공지사항 작성*/\r\n");
      out.write(".notice {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: -310px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공지 체크박스 */\r\n");
      out.write(".noticebox {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: -80px;\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공지사항 영역 */\r\n");
      out.write(".no-outbox {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: -465px;\r\n");
      out.write("	left: 490px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 공지사항 박스 */\r\n");
      out.write(".well {\r\n");
      out.write("	background-color: #EBF7FF;\r\n");
      out.write("	width: 591px;\r\n");
      out.write("	height: 55px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 타이틀-도덕 */\r\n");
      out.write("h3 {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 4%;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	width: 30%;\r\n");
      out.write("	height: 24px;\r\n");
      out.write("	-webkit-transform: translate(-50%, -50%);\r\n");
      out.write("	-ms-transform: translate(-50%, -50%);\r\n");
      out.write("	transform: translate(-50%, 100%);\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	text-shadow: -1px -1px 1px #aaa, 3px 3px 4px black;\r\n");
      out.write("	font-size: 45px;\r\n");
      out.write("	color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	font-family: \"맑은 고딕\";\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#bannerBox > ul{\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bannerBox2 > ul{\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/master.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/main.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/stream.js\"></script>\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"mbTypeCheck('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'); NoticeOutput(); getTaskDate(); getQuizDate(); getETCDate(); getNotice(); getAjax('https://api.ipify.org','format=json', 'getPublicIp');\">\r\n");
      out.write("	<input type='hidden' name='mbId' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("	<input type='hidden' name='csCode' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${csCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("	<input type='hidden' name='opCode' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${opCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("	<input type='hidden' name='opName' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${opName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("	<input type='hidden' name='mbType' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("	\r\n");
      out.write("	<nav  class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("	<div class=\"container-fluid\" style=\"display: flex;\">\r\n");
      out.write("		<div class=\"navbar-header\">\r\n");
      out.write("			<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#myNavbar\">\r\n");
      out.write("				<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("					class=\"icon-bar\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"#\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("			<ul class=\"nav navbar-nav\">\r\n");
      out.write("				<li><a href=\"main\" id=\"test\" style=\"color: white;\"><img\r\n");
      out.write("						src=\"resources/images/eljl_LOGO_final.png\"\r\n");
      out.write("						style=\"height: 30px; width: 100px;\" /></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id= \"bannerBox\" style=\"margin: 0 auto;\">\r\n");
      out.write("			<ul class=\"nav navbar-nav\">\r\n");
      out.write("				<li><a style=\"color: white;\" onClick=\"moveStream()\">스트림</a></li>\r\n");
      out.write("					<li><a  style=\"color: white;\" onClick=\"moveClass()\">수업</a></li>\r\n");
      out.write("					<li class=\"teItem\"><a  style=\"color: white;\" onClick=\"moveAttend()\">출석부</a></li>\r\n");
      out.write("					<li class=\"teItem\"><a  style=\"color: white;\" onClick=\"moveStuManage()\">학생관리</a></li>\r\n");
      out.write("					<li class=\"stuItem\"><a  style=\"color: white;\" onClick=\"moveMyPage()\">마이페이지</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"bannerBox2\">\r\n");
      out.write("			<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("				<li class=\"teItem\"><a onClick=\"moveSetting()\"><span class=\"glyphicon glyphicon-cog\"\r\n");
      out.write("						style=\"color: white;\"></span></a></li>\r\n");
      out.write("				<li><a style=\"color: white;\" onClick=\"logOut('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mbId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"><span\r\n");
      out.write("						class=\"glyphicon glyphicon-log-out\"></span> 로그아웃</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("	<!-- Wrapper for slides -->\r\n");
      out.write("	<!-- 학과명 타이틀 -->\r\n");
      out.write("	<div id=\"classTitle\">\r\n");
      out.write("		<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${opName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 일정 박스 -->\r\n");
      out.write("	<div class=\"container text-center\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div id=\"scfontbox-sfb\">\r\n");
      out.write("				<span id=\"scfont\">마감 과제 일정</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"scfontbox-sf\">\r\n");
      out.write("				<span id=\"scfont\">퀴즈 일정</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"scfontbox-sb\">\r\n");
      out.write("				<span id=\"scfont\">기타 일정</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-4\" id=\"TaskBoard\"></div>\r\n");
      out.write("			<div class=\"col-sm-4\" id=\"QuizBoard\"></div>\r\n");
      out.write("			<div class=\"col-sm-4\" id=\"ETCBoard\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 공지사항 -->\r\n");
      out.write("		<div class=\"notice\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<div class=\"noticebox\">\r\n");
      out.write("					<input type=\"radio\" class=\"btn-check\" name=\"options-outlined\" id=\"success-outlined\" autocomplete=\"off\" checked>\r\n");
      out.write("					<label class=\"btn btn-outline-important\" for=\"important-outlined\">중요공지</label>\r\n");
      out.write("                  \r\n");
      out.write("					<input type=\"radio\" class=\"btn-check\" name=\"options-outlined\" id=\"danger-outlined\" autocomplete=\"off\">\r\n");
      out.write("					<label class=\"btn btn-outline-general\" for=\"general-outlined\">일반공지</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("				<input id=\"titlebox\" class=\"textbox\" name=\"ntTitle\" placeholder=\"제목을 입력해주세요.\" />\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("				<input id=\"textbox\" class=\"textbox\" name=\"ntContents\" placeholder=\"내용을 입력해주세요.\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<input class=\"button\" type=\"button\" onClick=\"sendNotice()\" value=\"작성\" />\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<!-- 공지사항 출력 예시 박스 -->\r\n");
      out.write("		<div id=\"noticeBox\" class=\"no-outbox\">\r\n");
      out.write("			<div class=\"well\">\r\n");
      out.write("			<i class=\"fas fa-ellipsis-v\" style=\"margin-left: 540px;\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br> <br>\r\n");
      out.write("			<div class=\"well\">\r\n");
      out.write("			<i class=\"fas fa-ellipsis-v\" style=\"margin-left: 540px;\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br> <br>\r\n");
      out.write("			<div class=\"well\">\r\n");
      out.write("			<i class=\"fas fa-ellipsis-v\" style=\"margin-left: 540px;\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br> <br>\r\n");
      out.write("			<div class=\"well\">\r\n");
      out.write("			<i class=\"fas fa-ellipsis-v\" style=\"margin-left: 540px;\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 공지사항 보기 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"notice\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\" style=\"text-align:center;\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" onClick=\"deleteValue()\" >&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">공지사항</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body1\" style=\"text-align:center;\">\r\n");
      out.write("          <p>제목</p>\r\n");
      out.write("          <h6 id=\"ntTitle\"></h6>\r\n");
      out.write("          <p>내용</p>\r\n");
      out.write("          <div id=\"ntContents\"></div>\r\n");
      out.write("          <div id=\"ntBox\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-default\" onClick=\"updateNotice()\">수정</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" onClick=\"deleteNotice()\">삭제</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" >닫기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
